### ISSUE TITLE
Anim_Start event behavior.

### ISSUE THREAD

**Issue by Blttrr** [Chobolabs/spine-cpp#4]
If there are no playing animations on track, `AnimationState::addAnimation` method won't fire an  Anim_Start callback. `AnimationState::setAnimation` always fires it.

**Comment by pharan** [comment]
This is the same behavior as in the official runtime.
The fix is to replace addAnimation's [direct trackEntry[x] assignment](https://github.com/Chobolabs/spine-cpp/blob/master/src/spinecpp/AnimationState.cpp#L396) with a `setCurrent` call which does fire the Start callback.

We haven't applied this to the official runtime yet because the new AnimationState (in the dev branch) is just about ready and already addresses this.

**Comment by iboB** [comment]
Closing since it mimics the C API
