### ISSUE TITLE
AnimationState::setEmptyAnimation missing

### ISSUE THREAD

**Issue by andoalon** [Chobolabs/spine-cpp#6]
I was looking for the method that was the equivalent of spine-c's `spAnimationState_setEmptyAnimation`, but I couldn't find any method in `AnimationState` that is called `setEmptyAnimation`, as suggested by the official Spine API reference. Where can I find it? And if it doesn't exist, how can I get an equivalent result in my project?  Thank you in advance.

**Comment by iboB** [comment]
This is a feature from Spine 3.5, which is not supported yet. spine-cpp is still at 3.4. 

Unfortunately 3.5 (and later) support won't be available in spine-cpp for the next two months, because we won't have time to add the new features until then.

This particular feature, though, doesn't seem too hard to mimic in 3.4. You just need to create a new empty animation (`Animation empty("empty");`) and set it. However, if you use the Spine authoring tool for 3.5, there might be more issues that will break your software if you use spine-cpp.

**Comment by andoalon** [comment]
Thank you very much for the quick answer, but now I have a doubt: how can I make the skeleton mix from animation X to the empty animation? Sorry for my ignorance

**Comment by iboB** [comment]
I'm not exactly sure what the empty animation is in Spine 3.5, but if it is simply an animation with no timelines, then yes, you should be able to mix to it.

**Comment by andoalon** [comment]
Thank you for your help, I managed to get it to do what I wanted.
